DROP TABLE IF EXISTS m_department;
CREATE TABLE m_department (
  DEPARTMENT_ID int(11) NOT NULL AUTO_INCREMENT,
  DEPARTMENT_NAME varchar(255) NOT NULL,
  IS_DELETED tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (DEPARTMENT_ID)
);

-- $break$

DROP TABLE IF EXISTS m_employee;
CREATE TABLE m_employee (
  EMPLOYEE_ID int(11) NOT NULL AUTO_INCREMENT,
  EMPLOYEE_NAME varchar(255) NOT NULL,
  DEPARTMENT_ID int(11) NOT NULL,
  IS_DELETED tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES m_department(DEPARTMENT_ID) ON DELETE RESTRICT
);

select 'finish';