DROP TABLE IF EXISTS m_department;
CREATE TABLE m_department (
  DEPARTMENT_ID int(11) NOT NULL AUTO_INCREMENT,
  DEPARTMENT_NAME varchar(255) NOT NULL,
  IS_DELETED tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (DEPARTMENT_ID)
);

DROP TABLE IF EXISTS m_employee;
CREATE TABLE m_employee (
  EMPLOYEE_ID int(11) NOT NULL AUTO_INCREMENT,
  EMPLOYEE_NAME varchar(255) NOT NULL,
  DEPARTMENT_ID int(11) NOT NULL,
  IS_DELETED tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (EMPLOYEE_ID),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES m_department(DEPARTMENT_ID) ON DELETE RESTRICT
);

INSERT INTO m_department (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
  (1, '総務部'),
  (2, '営業部'),
  (3, '技術部');

INSERT INTO m_employee (EMPLOYEE_NAME, DEPARTMENT_ID) VALUES
  ("ジャワード マッハムード", 3),
  ("加藤 有希", 3),
  ("大沼 晶子", 1);